### ISSUE TITLE
Could not find publication, did you enter the correct name or id?

### ISSUE THREAD

**Issue by jerCarre** [philips-software/post-to-medium-action#16] opened 2021-12-22 07:47 UTC
Hello,

I try tu use this github action but I have this error : 

```
Unhandled exception. System.Exception: Could not find publication, did you enter the correct name or id?
   at PostMediumGitHubAction.Services.MediumService.SubmitNewContentAsync() in /Action/Services/MediumService.cs:line 28
   at PostMediumGitHubAction.Program.Main(String[] args) in /Action/Program.cs:line 19
   at PostMediumGitHubAction.Program.<Main>(String[] args)
```

My workflow : 

```
name: publish-to-medium
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./README.md)"
      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.3.4
        with:
          integration_token: "${{ secrets.MEDIUM_ACCESS_TOKEN }}"
          file: "./README.md"
          content_format: "markdown"
          publication_id: "PublicationName"
          publication_name: "publication"
          tags: "markdown,vega,vegalite,docsify,github"
          title: "Comment afficher le cours d'une crypto sur sa page github ?"
```

There's non article in medium.

Could you help me ?

**Comment by Brend-Smits** [comment] 2022-01-04 13:37
Hey @jerCarre,
Sorry for the delayed response. I missed this due to the holidays! 
The publication Name or Id has now been made optional so you can remove those. If you do not want to publish your article under a publication, you can leave them both out and it will automatically post it under the account of which you are authenticating. 

Your new workflow would be as follows:

```YAML
name: publish-to-medium
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./README.md)"
      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.4.0
        with:
          integration_token: "${{ secrets.MEDIUM_ACCESS_TOKEN }}"
          file: "./README.md"
          content_format: "markdown"
          tags: "markdown,vega,vegalite,docsify,github"
          title: "Comment afficher le cours d'une crypto sur sa page github ?"
```

I released a new version https://github.com/philips-software/post-to-medium-action/releases/tag/v0.4.0 to make this possible.

Thank you for opening a new issue, please let me know if you require additional help.

**Comment by jerCarre** [comment] 2022-01-04 14:11
Thank you for this new release but I have the same error :

**Comment by Brend-Smits** [comment] 2022-01-04 16:39
Thanks, I'm able to reproduce now: https://github.com/philips-software/post-to-medium-action/runs/4704659246?check_suite_focus=true#step:4:14
I will let you know when it's fixed!

**Comment by Brend-Smits** [comment] 2022-01-04 17:00
I released a new version that should fix this. Can you please verify @jerCarre?
See: https://github.com/philips-software/post-to-medium-action/releases/tag/v0.4.1
Make sure to change your workflow version from @v0.4.0 to @v0.4.1

**Comment by Brend-Smits** [comment] 2022-01-06 07:40
I will close this issue as I believe this has been resolved (checked your repository and it seems to be working now 😉) If not, please let me know.

**Closed by Brend-Smits** 2022-01-06 07:40 UTC

**Comment by jerCarre** [comment] 2022-01-06 15:04
It ok now. 

Thx
